### ISSUE TITLE
Opera browser support

### ISSUE THREAD

**Issue by Danp2** [Danp2/au3WebDriver#187] opened 2022-02-09 16:05 UTC
- [x] Update _WD_GetBrowserVersion
- [x] Update _WD_UpdateDriver
- [x] Update wd_capabilities.au3 to support Opera browser
- [x] Update readme.md
- [x] Test _WD_GetWebDriverVersion
- [x] Update wd_demo.au3

**Comment by mlipok** [comment] 2022-02-10 08:45
Recently it was mentioned here https://github.com/Danp2/WebDriver/pull/166
So as I understand here we have continuation ?

**Comment by Danp2** [comment] 2022-02-10 12:30
Correct. Here we can discuss the issue and track the progress. Let me know if there are any other steps / tasks that should be included above.

**Comment by mlipok** [comment] 2022-02-10 14:04
Please create separate branch on your side for this project.

**Comment by mlipok** [comment] 2022-02-12 10:39
For reference:
https://github.com/Danp2/au3WebDriver/tree/supportOpera

**Comment by Danp2** [comment] 2022-02-22 20:42
@mlipok @Sven-Seyfert Your feedback would be appreciated on the above draft PR.

FYI, the existing extraction code in `_WD_UpdateDriver` will need to be modified to work correctly on OperaDriver downloads because they store the .EXE in a subdirectory.

Also would like your input on how we can further eliminate hardcoding of browser names, paths, etc.

**Comment by mlipok** [comment] 2022-02-23 12:58
Please add new task to the list in OP.
wd_capabilities.au3 should be suplemented to support Opera browser

**Comment by Danp2** [comment] 2022-02-23 13:13
Yes, I think that's a good idea. If you target the `supportOpera` branch, then these individual PRs can be merged simultaneously from #213

**Comment by Danp2** [comment] 2022-02-23 13:28
@mlipok See `$_WD_SupportedBrowsers`, which is now located in wd_core.au3 (supportOpera branch). I just added the `Browser options key` column, which you can use in `__WD_CapabilitiesInitialize` to eliminate hardcoding of specific browser info (see https://github.com/Danp2/au3WebDriver/pull/213/commits/0de1eed9c37c93dfa22db7e0a5f066638d2be458 for example).

**Comment by mlipok** [comment] 2022-02-23 13:54
Please use different name for this issue and for [PR#213: Add support for Opera browser](https://github.com/Danp2/au3WebDriver/pull/213)

**Comment by Danp2** [comment] 2022-02-23 13:56
> Please use different name for this issue and for https://github.com/Danp2/au3WebDriver/pull/213

Why? What would you propose instead?

**Comment by mlipok** [comment] 2022-02-23 14:02
Why:
It confuse me a little sometimes when I see the same name

in notification list
![image](https://user-images.githubusercontent.com/11089482/155334210-ce32284e-1848-4d82-9433-bd10ae7c1eb9.png)

and 
in browser tabs
![image](https://user-images.githubusercontent.com/11089482/155334295-56bf7758-8e0d-4859-9dc8-6ba67cccb955.png)


For example:

**ISSUE:** `Task: support for Opera browser` or `TODO: support for Opera browser`

**PR:** `Support for Opera browser`

**Comment by Danp2** [comment] 2022-02-23 16:24
>  It confuse me a little sometimes when I see the same name

FWIW, the icons indicate the type of item (PR, issue, etc).

**Comment by mlipok** [comment] 2022-02-23 19:24
Please merge: https://github.com/Danp2/au3WebDriver/pull/215
to: https://github.com/Danp2/au3WebDriver/tree/supportOpera

**Comment by Sven-Seyfert** [comment] 2022-02-23 22:41
> Dan: Also would like your input on how we can further eliminate hardcoding of browser names, paths, etc.

You mean all kinds of browser properties outside of the several `wd_*.au3` files? Because any time there has to be a change, it has to be in several files, right? Sounds like a real nice idea 👍 .

Do we need it to be configurable without adjusting AutoIt code?
- Then the old school way of using a INI file could be helpful.
- Or even better by SQLite.
But I don't see the need of any of these.

Why not simple create a `wd_constants.au3` / `wd_browser_constants.au3` with all the names, the paths, etc. and `#include` this file into to different other `wd_*.au3` files? This would be pretty handy 😅 .

**Comment by Danp2** [comment] 2022-02-23 22:51
I was actually referring to functions like `_WD_UpdateDriver` that currently have hard coded browser names. I'm not sure if @mlipok has done any work on that one yet.

I seem to recall that there was resistance from others (I think it was on the forum) to usage of external files due to the need to remember to distribute them.

`wd_constants.au3` might be handy as a way to have them all in one location.

**Comment by mlipok** [comment] 2022-02-23 22:53
> I'm not sure if @mlipok has done any work on that one yet.

You already provide some with `$_WD_SupportedBrowsers` and `Case 'opera'` my work will be related to unpacking subdirectory.

**Comment by mlipok** [comment] 2022-02-23 22:55
> I'm not sure if @mlipok has done any work on that one yet.

Not yet.

**Comment by Danp2** [comment] 2022-02-23 23:09
It would be great if we could eliminate the hard coded browser names in _WD_UpdateDriver. Maybe if you, @Sven-Seyfert & I can come up with a good solution if we put our heads together.

**Comment by Danp2** [comment] 2022-02-24 12:33
> You already provide some changes with `$_WD_SupportedBrowsers` and `Case 'opera'` .
> My work will be related to unpacking subdirectory.

Instead of trying to traverse the complete zip file structure, couldn't we just extract the entire file to a temp directory and then grab a list of any executables with _FileListToArrayRec?

**Comment by mlipok** [comment] 2022-02-24 12:39
And my plan is to move extracting to separate internall function

**Comment by Danp2** [comment] 2022-02-24 19:41
Found https://github.com/operasoftware/operachromiumdriver/issues/97#issuecomment-967210876. Given this and #220, I wonder if we should alter our plans?

**Comment by Sven-Seyfert** [comment] 2022-02-24 20:11
Agreed. In my opinion we should revert almost all Opera support actions and notify the users in the ReadMe file what they can do if they want to use Opera. But maybe @mlipok disagrees?

**Comment by mlipok** [comment] 2022-02-24 20:41
Give some time. Max 1 week.
I will do research.

**Comment by Sven-Seyfert** [comment] 2022-02-24 20:53
> It would be great if we could eliminate the hard coded browser names in _WD_UpdateDriver. Maybe if you, @Sven-Seyfert & I can come up with a good solution if we put our heads together.

I reviewed the current solution to be flexible regarding finding the values of `$_WD_SupportedBrowsers`.

- Enum values,
- 2D Array (table of content),
- _ArraySearch() action to get the index,
- Usage of this index to find the actually `$_WD_SupportedBrowsers` value.

The idea is not bad and I like the generic approach 😀 . Unfortunately I have to say it's also quite hard to understand and a bit of redundant 🤔 .

I would suggest something like the following which doesn't need the enum values and **could** be a bit simpler.
It's not complete, but I believe you will understand how I am thinking.

``` autoit
#include-once
#include <Array.au3>

Global $_WD_SupportedBrowsers[][8] = _
    [ _
        ["BrowserName", "BrowserExe", "DriverExe", "IsBrowserArchX64", "BrowserOptionsKey", "BrowserLatestUrl", "BrowserZipDownloadUrl", "BrowserZipPrefix"], _
        ["chrome", "chrome.exe", "chromedriver.exe", False, "goog:chromeOptions", "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_", "https://chromedriver.storage.googleapis.com/", "/chromedriver_"], _
        ["firefox", "firefox.exe", "geckodriver.exe", True, "moz:firefoxOptions", "https://github.com/mozilla/geckodriver/releases/latest", "https://github.com/mozilla/geckodriver/releases/download/v", "/geckodriver-v"], _
        ["msedge", "msedge.exe", "msedgedriver.exe", True, "ms:edgeOptions", "https://msedgedriver.azureedge.net/LATEST_RELEASE_", "https://msedgedriver.azureedge.net/", "/edgedriver_"], _
        ["opera", "opera.exe", "operadriver.exe", True, "operaOptions", "https://github.com/operasoftware/operachromiumdriver/releases/latest", "https://github.com/operasoftware/operachromiumdriver/releases/download/v.", "/operadriver_"] _
    ]

_ArrayDisplay($_WD_SupportedBrowsers)

ConsoleWrite('Example 1: ' & _GetBrowserProperty('CHROME', 'BrowserOptionsKey') & @CRLF)
ConsoleWrite('Example 2: ' & _GetBrowserProperty('FireFox', 'IsBrowserArchX64') & @CRLF)
ConsoleWrite('Example 3: ' & _GetBrowserProperty('opera', 'DRIVEREXE') & @CRLF)
ConsoleWrite('Example 4: ' & _GetBrowserProperty('Msedge', 'BrowserZipPrefix') & @CRLF)

Func _GetBrowserProperty($sBrowserName, $sProperty)
    Local $iRowCount = UBound($_WD_SupportedBrowsers, 1) - 1

    For $i = 0 To $iRowCount Step 1
        If StringLower($_WD_SupportedBrowsers[$i][0]) == StringLower($sBrowserName) Then
            Local $iRow = $i
            ExitLoop
        EndIf
    Next

    Local $iColumnCount = UBound($_WD_SupportedBrowsers, 2) - 1

    For $i = 0 To $iColumnCount Step 1
        If StringLower($_WD_SupportedBrowsers[0][$i]) == StringLower($sProperty) Then
            Local $iColumn = $i
            ExitLoop
        EndIf
    Next

    Return $_WD_SupportedBrowsers[$iRow][$iColumn]
EndFunc

```
The different upper or lower case for the `_GetBrowserProperty` parameters is just a show case that it doesn't matter.

![grafik](https://user-images.githubusercontent.com/29656921/155605021-df065990-964c-4994-b3ad-b53c9a37159d.png)

I hope this will provide the best of the two approaches to get the browser property 🤞 .

**Comment by Sven-Seyfert** [comment] 2022-02-24 21:46
> Give some time. Max 1 week.
> I will do research.

No stress and pressure at all from my perspective 😇 .
As long as we merge possible other code changes into this branch, in the meanwhile, we don't have got problems with the PR.

**Comment by Danp2** [comment] 2022-02-24 23:02
@mlipok @Sven-Seyfert Crisis averted. 😆  See my latest post in #220.

**Comment by Danp2** [comment] 2022-02-24 23:21
@Sven-Seyfert 

> Unfortunately I have to say it's also quite hard to understand and a bit of redundant 🤔 .

Please elaborate. Which part was difficult to understand? Which part would you consider redundant?

> I would suggest something like the following which doesn't need the enum values and could be a bit simpler.

That's an interesting concept where you are embedding the equivalent of the enums in the first row. I'm unsure which I prefer. One downside to your method is that each lookup requires to search for the browser in the array instead of looking up the index once and then reusing it as needed. 

I also think that it is important to remember who will be using either of these methods... us!! The user of these UDFs don't need to access $_WD_SupportedBrowsers directly; they simple call the functions that we provide. 🙂

**Comment by mlipok** [comment] 2022-02-25 09:33
> @mlipok @Sven-Seyfert Crisis averted. 😆 See my latest post in #220.

Confirmed. Your capabilites strings works for me.
```json
{
    "capabilities":{
        "alwaysMatch":{
            "goog:chromeOptions":{
                "w3c":true,
                "excludeSwitches":[
                    "enable-automation"
                ],
                "binary":"C:\\Users\\Szef\\AppData\\Local\\Programs\\Opera\\opera.exe"
            }
        }
    }
}
```

**Comment by Sven-Seyfert** [comment] 2022-02-25 10:52
@Danp2 @mlipok 

Just FYI: I am a bit sad 😔 . Why? Unfortunately I am not able to provide such quick responses or reactions like you both do. In case of questions or "mentions" within my daily work time, I can only response few hours or sometimes even few days later.
This will not change in general, but I do my best to participate as much as I can without kipping family time.

Nevertheless I will respond to your questions Dan, today. Will be a bit of explanation effort, but I guess it is worthy 😅 .

**Comment by mlipok** [comment] 2022-02-25 20:53
I notice that in case using this UDF with operadriver.exe you will see two different console window
![image](https://user-images.githubusercontent.com/11089482/155801191-57c59fdb-b9f7-4fcd-9895-4a0068b376f0.png)

Can somebody check it, confirm, check if its hide.

**Comment by Danp2** [comment] 2022-02-25 20:59
Yes, I noticed that this occurs if you don't change `launcher` to `opera`. I previously showed how I changed the `SetupOpera` code in #223

**Comment by mlipok** [comment] 2022-02-25 21:01
I'm using `opera` not `launcher` using `launcher.exe` dosen't run browser at all in my case (maybe in 32bit as I not check it on 64bit driver)

**Comment by mlipok** [comment] 2022-02-25 21:03
btw.
I think that [wd_demo.au3](https://github.com/Danp2/au3WebDriver/pull/218) is ready to merge.

**Comment by Danp2** [comment] 2022-02-25 21:30
> I'm using opera not launcher

That's what I'm doing as well. I just handle the "exception" outside of `_WD_GetBrowserPath`. My goal was to eliminate browser specific code from the UDF's functions. Performing this activity inside `_WD_GetBrowserPath` doesn't support this goal.

**Comment by mlipok** [comment] 2022-02-25 22:55
> My goal was to eliminate browser specific code from the UDF's functions. Performing this activity inside `_WD_GetBrowserPath` doesn't support this goal.

Unfortunately, this will sometimes be impossible.
In this case, it's just one extra line.
Alternatively, we can parse the path to get only the directory and then put the filename from the variable: $_WD_SupportedBrowsers

Like this:
```AutoIt
$sPath = StringRegExpReplace($sPath, '(.+\\)(.*exe)', '$1' & $sEXE) ; Registry entries can contain "Launcher.exe" instead "opera.exe"
```

And this will fit all cases.

**Comment by mlipok** [comment] 2022-02-25 22:58
But on the other hand.
What if I want to use my own predefined directory for PortableBrowser ?
or use one of few installed version of the same browser and automatically update driver for each version?

**Comment by Danp2** [comment] 2022-02-26 00:13
> Alternatively, we can parse the path to get only the directory and then put the filename from the variable: $_WD_SupportedBrowsers

Yes, that would be a better solution in my mind

> But on the other hand. What if I want to use my own predefined directory for PortableBrowser ?
> or use one of few installed version of the same browser and automatically update driver for each version?

This isn't how `_WD_UpdateDriver` was designed to function. However, it should be possible to modify it to handle this scenario.

**Comment by mlipok** [comment] 2022-02-26 22:52
So all is merged.

Tomorow I take a look on _WD_UpdateDriver
And Enums

Now going to bed.

**Comment by mlipok** [comment] 2022-03-02 20:38
As you merege my latest PR is that mean that this task list is completed ?

**Closed** 2022-03-02 21:39 UTC
Labels: enhancement
